import React, { useState, useEffect } from 'react';
import { X, MessageSquare, Calendar, Download, Printer, Copy, Check, ExternalLink, Sparkles } from 'lucide-react';
import { getCoachExcelUrl, getCoachIcsUrl, getCoachWhatsAppMsg } from '../services/api';

export default function CoachDispatchModal({ isOpen, onClose, coachName, scheduleId }) {
  const [whatsappText, setWhatsappText] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState('whatsapp');

  useEffect(() => {
    if (isOpen && coachName && scheduleId) {
      fetchWhatsAppText();
    }
  }, [isOpen, coachName, scheduleId]);

  const fetchWhatsAppText = async () => {
    setLoading(true);
    try {
      const res = await getCoachWhatsAppMsg(scheduleId, coachName);
      if (res && res.whatsapp_text) {
        setWhatsappText(res.whatsapp_text);
      }
    } catch (err) {
      console.error('Failed to fetch WhatsApp text:', err);
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen || !coachName) return null;

  const excelUrl = getCoachExcelUrl(scheduleId, coachName);
  const icsUrl = getCoachIcsUrl(scheduleId, coachName);

  const handleCopyText = async () => {
    try {
      await navigator.clipboard.writeText(whatsappText);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (err) {
      alert('Failed to copy: ' + err.message);
    }
  };

  const handleOpenWhatsAppWeb = () => {
    const encoded = encodeURIComponent(whatsappText);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  };

  const handlePrintPDF = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Mighty Knight - Schedule for Coach ${coachName}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 30px; color: #111; }
            h1 { color: #d97706; margin-bottom: 5px; }
            h2 { color: #374151; font-size: 1.1rem; margin-top: 0; }
            pre { background: #f3f4f6; padding: 20px; border-radius: 8px; font-family: monospace; white-space: pre-wrap; word-wrap: break-word; font-size: 0.95rem; border: 1px solid #e5e7eb; }
            .footer { margin-top: 30px; font-size: 0.8rem; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 10px; }
          </style>
        </head>
        <body>
          <h1>🏆 Mighty Knight Chess Academy</h1>
          <h2>Official Weekly Schedule — Coach ${coachName}</h2>
          <pre>${whatsappText}</pre>
          <div class="footer">Generated by Mighty Knight Scheduler System • ${new Date().toLocaleString()}</div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0, 0, 0, 0.75)',
        backdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
        padding: '20px'
      }}
    >
      <div
        className="glass-panel"
        style={{
          width: '100%',
          maxWidth: '680px',
          background: 'var(--bg-secondary)',
          borderRadius: 'var(--radius-lg)',
          border: '1px solid var(--accent-gold)',
          overflow: 'hidden',
          boxShadow: '0 20px 50px rgba(0,0,0,0.8)'
        }}
      >
        {/* Modal Header */}
        <div
          style={{
            padding: '20px 24px',
            background: 'var(--bg-card)',
            borderBottom: '1px solid var(--border-color)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: 'var(--accent-gold)',
                color: '#000',
                fontWeight: 800,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
              }}
            >
              {coachName.charAt(0).toUpperCase()}
            </div>
            <div>
              <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#fff' }}>
                📲 Dispatch Schedule — Coach {coachName}
              </h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                Choose export format, send via WhatsApp, or generate .ics calendar file.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Modal Navigation Tabs */}
        <div style={{ display: 'flex', borderBottom: '1px solid var(--border-color)', background: 'rgba(0,0,0,0.2)' }}>
          <button
            onClick={() => setActiveTab('whatsapp')}
            style={{
              flex: 1,
              padding: '12px',
              border: 'none',
              background: activeTab === 'whatsapp' ? 'var(--bg-secondary)' : 'transparent',
              color: activeTab === 'whatsapp' ? '#25D366' : 'var(--text-secondary)',
              fontWeight: 700,
              fontSize: '0.825rem',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '6px',
              borderBottom: activeTab === 'whatsapp' ? '2px solid #25D366' : 'none'
            }}
          >
            <MessageSquare size={16} /> WhatsApp Message
          </button>

          <button
            onClick={() => setActiveTab('ics')}
            style={{
              flex: 1,
              padding: '12px',
              border: 'none',
              background: activeTab === 'ics' ? 'var(--bg-secondary)' : 'transparent',
              color: activeTab === 'ics' ? 'var(--accent-blue)' : 'var(--text-secondary)',
              fontWeight: 700,
              fontSize: '0.825rem',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '6px',
              borderBottom: activeTab === 'ics' ? '2px solid var(--accent-blue)' : 'none'
            }}
          >
            <Calendar size={16} /> .ics Calendar Sync
          </button>

          <button
            onClick={() => setActiveTab('excel')}
            style={{
              flex: 1,
              padding: '12px',
              border: 'none',
              background: activeTab === 'excel' ? 'var(--bg-secondary)' : 'transparent',
              color: activeTab === 'excel' ? 'var(--accent-gold)' : 'var(--text-secondary)',
              fontWeight: 700,
              fontSize: '0.825rem',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '6px',
              borderBottom: activeTab === 'excel' ? '2px solid var(--accent-gold)' : 'none'
            }}
          >
            <Download size={16} /> Excel Sheet
          </button>
        </div>

        {/* Modal Body */}
        <div style={{ padding: '24px' }}>
          {/* TAB 1: WHATSAPP MESSAGE */}
          {activeTab === 'whatsapp' && (
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                  Formatted WhatsApp Schedule Broadcast Text:
                </span>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button
                    onClick={handleCopyText}
                    className="btn btn-secondary"
                    style={{ padding: '4px 10px', fontSize: '0.75rem' }}
                  >
                    {copied ? <Check size={14} style={{ color: '#10b981' }} /> : <Copy size={14} />}
                    {copied ? 'Copied!' : 'Copy Text'}
                  </button>
                  <button
                    onClick={handlePrintPDF}
                    className="btn btn-secondary"
                    style={{ padding: '4px 10px', fontSize: '0.75rem' }}
                  >
                    <Printer size={14} /> Print PDF
                  </button>
                </div>
              </div>

              <textarea
                value={whatsappText}
                onChange={e => setWhatsappText(e.target.value)}
                rows={10}
                style={{
                  width: '100%',
                  padding: '12px',
                  borderRadius: 'var(--radius-md)',
                  background: 'var(--bg-card)',
                  border: '1px solid var(--border-color)',
                  color: '#fff',
                  fontFamily: 'monospace',
                  fontSize: '0.825rem',
                  resize: 'vertical',
                  marginBottom: '16px'
                }}
              />

              <button
                onClick={handleOpenWhatsAppWeb}
                className="btn btn-primary"
                style={{ width: '100%', padding: '12px', background: '#25D366', borderColor: '#25D366', color: '#fff', fontWeight: 800, fontSize: '0.9rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}
              >
                <ExternalLink size={18} /> Open WhatsApp Web & Send to Coach {coachName}
              </button>
            </div>
          )}

          {/* TAB 2: ICS CALENDAR SYNC */}
          {activeTab === 'ics' && (
            <div style={{ textAlign: 'center', padding: '10px 0' }}>
              <div style={{ width: '56px', height: '56px', borderRadius: '16px', background: 'rgba(59, 130, 246, 0.2)', color: 'var(--accent-blue)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px auto', border: '1px solid var(--accent-blue)' }}>
                <Calendar size={32} />
              </div>
              <h4 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#fff', marginBottom: '8px' }}>
                📅 Automatic Calendar Sync (.ics File)
              </h4>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', maxWidth: '460px', margin: '0 auto 24px auto', lineHeight: 1.5 }}>
                Opening the downloaded <strong>.ics calendar file</strong> on iPhones, Android phones, Macs, or Windows PCs automatically adds all assigned chess class slots directly to Google Calendar, Apple Calendar, or Outlook with full student lists!
              </p>

              <a
                href={icsUrl}
                download={`mighty_knight_${coachName}_calendar.ics`}
                className="btn btn-primary"
                style={{ textDecoration: 'none', padding: '12px 28px', fontSize: '0.9rem', display: 'inline-flex', alignItems: 'center', gap: '8px' }}
              >
                <Download size={18} /> Download Coach {coachName} Calendar (.ics)
              </a>
            </div>
          )}

          {/* TAB 3: EXCEL SPREADSHEET */}
          {activeTab === 'excel' && (
            <div style={{ textAlign: 'center', padding: '10px 0' }}>
              <div style={{ width: '56px', height: '56px', borderRadius: '16px', background: 'rgba(234, 179, 8, 0.2)', color: 'var(--accent-gold)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px auto', border: '1px solid var(--accent-gold)' }}>
                <Download size={32} />
              </div>
              <h4 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#fff', marginBottom: '8px' }}>
                📊 Dedicated Excel Schedule (.xlsx)
              </h4>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', maxWidth: '460px', margin: '0 auto 24px auto', lineHeight: 1.5 }}>
                Includes 2 formatted spreadsheet worksheets: <strong>Timetable Schedule</strong> (Day, Time, Level, Batch, Student List) and <strong>Student Rosters</strong> (Student IDs and Names).
              </p>

              <a
                href={excelUrl}
                download={`mighty_knight_${coachName}_schedule.xlsx`}
                className="btn btn-primary"
                style={{ textDecoration: 'none', padding: '12px 28px', fontSize: '0.9rem', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'var(--accent-gold)', borderColor: 'var(--accent-gold)', color: '#000', fontWeight: 800 }}
              >
                <Download size={18} /> Download Excel Spreadsheet (.xlsx)
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
