import React, { useState, useEffect } from 'react';
import { X, MessageSquare, Calendar, Download, Printer, Copy, Check, ExternalLink, Sparkles, CheckSquare, Square, Zap } from 'lucide-react';
import { getCoachExcelUrl, getCoachIcsUrl, getCoachWhatsAppMsg } from '../services/api';

export default function CoachDispatchModal({ isOpen, onClose, coachName, scheduleId }) {
  const [whatsappText, setWhatsappText] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  
  // Multi-select format checkboxes
  const [selectExcel, setSelectExcel] = useState(true);
  const [selectIcs, setSelectIcs] = useState(true);
  const [selectWhatsApp, setSelectWhatsApp] = useState(true);
  const [dispatching, setDispatching] = useState(false);

  useEffect(() => {
    if (isOpen && coachName && scheduleId) {
      fetchWhatsAppText();
    }
  }, [isOpen, coachName, scheduleId]);

  const fetchWhatsAppText = async () => {
    setLoading(true);
    try {
      const res = await getCoachWhatsAppMsg(scheduleId, coachName);
      if (res && res.whatsapp_text) {
        setWhatsappText(res.whatsapp_text);
      }
    } catch (err) {
      console.error('Failed to fetch WhatsApp text:', err);
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen || !coachName) return null;

  const excelUrl = getCoachExcelUrl(scheduleId, coachName);
  const icsUrl = getCoachIcsUrl(scheduleId, coachName);

  const handleCopyText = async () => {
    try {
      await navigator.clipboard.writeText(whatsappText);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (err) {
      alert('Failed to copy: ' + err.message);
    }
  };

  const triggerDownload = (url, filename) => {
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleDispatchAllSelected = async () => {
    setDispatching(true);
    try {
      // 1. Download Excel if selected
      if (selectExcel) {
        triggerDownload(excelUrl, `mighty_knight_${coachName}_schedule.xlsx`);
      }

      // 2. Download .ics if selected (short delay to prevent browser block)
      if (selectIcs) {
        setTimeout(() => {
          triggerDownload(icsUrl, `mighty_knight_${coachName}_calendar.ics`);
        }, 400);
      }

      // 3. Open WhatsApp Web if selected
      if (selectWhatsApp) {
        await navigator.clipboard.writeText(whatsappText);
        setCopied(true);
        setTimeout(() => setCopied(false), 3000);

        const appendNote = whatsappText + "\n\n📎 *Note:* Attached your Excel timetable (.xlsx) and Calendar Sync file (.ics) for automatic Google/Apple Calendar import!";
        const encoded = encodeURIComponent(appendNote);
        setTimeout(() => {
          window.open(`https://wa.me/?text=${encoded}`, '_blank');
        }, 800);
      }
    } catch (err) {
      alert('Dispatch failed: ' + err.message);
    } finally {
      setDispatching(false);
    }
  };

  const handlePrintPDF = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Mighty Knight - Schedule for Coach ${coachName}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 30px; color: #111; }
            h1 { color: #d97706; margin-bottom: 5px; }
            h2 { color: #374151; font-size: 1.1rem; margin-top: 0; }
            pre { background: #f3f4f6; padding: 20px; border-radius: 8px; font-family: monospace; white-space: pre-wrap; word-wrap: break-word; font-size: 0.95rem; border: 1px solid #e5e7eb; }
            .footer { margin-top: 30px; font-size: 0.8rem; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 10px; }
          </style>
        </head>
        <body>
          <h1>🏆 Mighty Knight Chess Academy</h1>
          <h2>Official Weekly Schedule — Coach ${coachName}</h2>
          <pre>${whatsappText}</pre>
          <div class="footer">Generated by Mighty Knight Scheduler System • ${new Date().toLocaleString()}</div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0, 0, 0, 0.75)',
        backdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
        padding: '20px'
      }}
    >
      <div
        className="glass-panel"
        style={{
          width: '100%',
          maxWidth: '720px',
          background: 'var(--bg-secondary)',
          borderRadius: 'var(--radius-lg)',
          border: '1px solid var(--accent-gold)',
          overflow: 'hidden',
          boxShadow: '0 20px 50px rgba(0,0,0,0.8)'
        }}
      >
        {/* Modal Header */}
        <div
          style={{
            padding: '20px 24px',
            background: 'var(--bg-card)',
            borderBottom: '1px solid var(--border-color)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div
              style={{
                width: '44px',
                height: '44px',
                borderRadius: '50%',
                background: 'var(--accent-gold)',
                color: '#000',
                fontWeight: 800,
                fontSize: '1.2rem',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
              }}
            >
              {coachName.charAt(0).toUpperCase()}
            </div>
            <div>
              <h3 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#fff' }}>
                📲 Multi-Format Dispatch — Coach {coachName}
              </h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                Select formats to include (Excel + .ics Calendar Sync + WhatsApp) & dispatch simultaneously!
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Multi-Select Formats Chooser Panel */}
        <div style={{ padding: '20px 24px', background: 'rgba(0,0,0,0.2)', borderBottom: '1px solid var(--border-color)' }}>
          <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--accent-gold)', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Zap size={16} /> SELECT ALL FORMATS TO DISPATCH:
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px' }}>
            {/* Checkbox 1: Excel Sheet */}
            <div
              onClick={() => setSelectExcel(!selectExcel)}
              style={{
                background: selectExcel ? 'rgba(234, 179, 8, 0.15)' : 'var(--bg-card)',
                border: selectExcel ? '1px solid var(--accent-gold)' : '1px solid var(--border-color)',
                borderRadius: 'var(--radius-sm)',
                padding: '10px 14px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '10px'
              }}
            >
              <input
                type="checkbox"
                checked={selectExcel}
                onChange={() => {}}
                style={{ cursor: 'pointer' }}
              />
              <div>
                <div style={{ fontSize: '0.825rem', fontWeight: 700, color: '#fff', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <Download size={14} style={{ color: 'var(--accent-gold)' }} /> Excel Sheet (.xlsx)
                </div>
                <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Timetable & Student Rosters</div>
              </div>
            </div>

            {/* Checkbox 2: iCalendar Sync */}
            <div
              onClick={() => setSelectIcs(!selectIcs)}
              style={{
                background: selectIcs ? 'rgba(59, 130, 246, 0.15)' : 'var(--bg-card)',
                border: selectIcs ? '1px solid var(--accent-blue)' : '1px solid var(--border-color)',
                borderRadius: 'var(--radius-sm)',
                padding: '10px 14px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '10px'
              }}
            >
              <input
                type="checkbox"
                checked={selectIcs}
                onChange={() => {}}
                style={{ cursor: 'pointer' }}
              />
              <div>
                <div style={{ fontSize: '0.825rem', fontWeight: 700, color: '#fff', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <Calendar size={14} style={{ color: 'var(--accent-blue)' }} /> Calendar Sync (.ics)
                </div>
                <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Google/Apple Calendar File</div>
              </div>
            </div>

            {/* Checkbox 3: WhatsApp Text */}
            <div
              onClick={() => setSelectWhatsApp(!selectWhatsApp)}
              style={{
                background: selectWhatsApp ? 'rgba(37, 211, 102, 0.15)' : 'var(--bg-card)',
                border: selectWhatsApp ? '1px solid #25D366' : '1px solid var(--border-color)',
                borderRadius: 'var(--radius-sm)',
                padding: '10px 14px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '10px'
              }}
            >
              <input
                type="checkbox"
                checked={selectWhatsApp}
                onChange={() => {}}
                style={{ cursor: 'pointer' }}
              />
              <div>
                <div style={{ fontSize: '0.825rem', fontWeight: 700, color: '#fff', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <MessageSquare size={14} style={{ color: '#25D366' }} /> WhatsApp Message
                </div>
                <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Tailored WhatsApp Text</div>
              </div>
            </div>
          </div>

          {/* Combined Dispatch Action Button */}
          <button
            onClick={handleDispatchAllSelected}
            disabled={dispatching || (!selectExcel && !selectIcs && !selectWhatsApp)}
            className="btn btn-primary"
            style={{
              width: '100%',
              marginTop: '16px',
              padding: '12px',
              fontSize: '0.95rem',
              fontWeight: 800,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px'
            }}
          >
            <Zap size={18} />
            {dispatching
              ? 'Dispatching Files...'
              : `🚀 Dispatch Selected Formats (${[selectExcel && 'Excel', selectIcs && '.ics Calendar', selectWhatsApp && 'WhatsApp'].filter(Boolean).join(' + ')})`}
          </button>
        </div>

        {/* Live Preview Text & Individual Buttons */}
        <div style={{ padding: '20px 24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
              Live Schedule Text Preview:
            </span>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button
                onClick={handleCopyText}
                className="btn btn-secondary"
                style={{ padding: '4px 10px', fontSize: '0.75rem' }}
              >
                {copied ? <Check size={14} style={{ color: '#10b981' }} /> : <Copy size={14} />}
                {copied ? 'Copied!' : 'Copy Text'}
              </button>
              <button
                onClick={handlePrintPDF}
                className="btn btn-secondary"
                style={{ padding: '4px 10px', fontSize: '0.75rem' }}
              >
                <Printer size={14} /> Print PDF
              </button>
            </div>
          </div>

          <textarea
            value={whatsappText}
            onChange={e => setWhatsappText(e.target.value)}
            rows={7}
            style={{
              width: '100%',
              padding: '12px',
              borderRadius: 'var(--radius-md)',
              background: 'var(--bg-card)',
              border: '1px solid var(--border-color)',
              color: '#fff',
              fontFamily: 'monospace',
              fontSize: '0.8rem',
              resize: 'vertical'
            }}
          />
        </div>
      </div>
    </div>
  );
}
