from typing import List, Dict
from datetime import datetime
from app.models.schedule import ScheduleResult, CoachCommunicationSlot
from app.utils.time_utils import parse_time_slot_sort_key

def generate_coach_schedule_text(result: ScheduleResult) -> str:
    """
    Generates Output 1 WhatsApp-ready plain text (BRD Section 34).
    Contains only: Date, Day, Time, and Coach names. Clean, sorted chronologically, and ready for WhatsApp.
    """
    if not result.coach_schedule:
        return "No classes scheduled for the selected period."

    lines = []
    lines.append("🏆 *MIGHTY KNIGHT — COACH SCHEDULE*")
    lines.append(f"Period: {result.start_date} to {result.end_date}")
    lines.append("=================================")

    # Group by date
    dates_map: Dict[str, List[CoachCommunicationSlot]] = {}
    for slot in result.coach_schedule:
        if slot.date not in dates_map:
            dates_map[slot.date] = []
        dates_map[slot.date].append(slot)

    for d_str in sorted(dates_map.keys()):
        slots = dates_map[d_str]
        # Sort slots by start time chronologically
        slots.sort(key=lambda s: parse_time_slot_sort_key(s.date, s.time_slot))

        try:
            date_obj = datetime.strptime(d_str, "%Y-%m-%d")
            formatted_date = date_obj.strftime("%A, %B %d, %Y")
        except ValueError:
            formatted_date = d_str

        lines.append("")
        lines.append(f"📅 *{formatted_date}*")
        lines.append("---------------------------------")

        for s in slots:
            coaches_str = ", ".join(s.coaches)
            lines.append(f"• *{s.time_slot}*: {coaches_str}")

    lines.append("")
    lines.append("=================================")
    lines.append("Generated by Mighty Knight Scheduling Engine")

    return "\n".join(lines)
